*: Implement the List interface for TfJobList (#278)
The error is caused by the field name in TfJobList:

// TfJobList is a list of TfJobs clusters.
type TfJobList struct {
	metav1.TypeMeta `json:",inline"`
	// Standard list metadata
	// More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#metadata
	Metadata metav1.ListMeta `json:"metadata,omitempty"`
	// Items is a list of TfJobs
	Items []TfJob `json:"items"`
}
The name of field Metadata should be anonymous field.

ERROR: logging before flag.Parse: E0110 16:52:24.998866    3707 runtime.go:66] Observed a panic: &errors.errorString{s:"*v1alpha1.TfJobList does not implement the List interface"} (*v1alpha1.TfJobList does not implement the List interface)